### PR TITLE
Change EMEA meeting timezone

### PR DESCRIPTION
**Pull request by raesene**
This changes the EMEA meeting timezone from BST to UTC

Signed-off-by: Rory McCune <raesene@gmail.com>

### CODE REVIEW

**Review by lumjjb — APPROVED** [review]
LGTM. but want to see if this works as intended for @sublimino since he's mostly going to be on this meeting

**Comment by sudo-bmitch** [comment]
UTC doesn't have DST. I think the goal was to be based on UK time so that it will spring forward again in a few months.

**Comment by lumjjb** [comment]
minor lint err: `README.md:130:81 MD013/line-length Line length [Expected: 80; Actual: 131]`

**Comment by raesene** [comment]
@sudo-bmitch that is true, problem with not using UTC is (as we noticed today) it can be ambiguous. If the intent is to keep it as "1pm UK time" then either the page will need updating a couple of times a year, or we can write "1pm UK Time" which feels a bit anglo-centric.

**Comment by raesene** [comment]
@lumjjb I did notice that Lint error but as this change *shouldn't* be changing line lengths, I guessed it was a pre-existing thing, so didn't want to mess with it :)

**Comment by sublimino** [comment]
@raesene cheers, I updated to "London time" to save us changing back again in six months

**Pull request merged**
