### PR TITLE
CII -> OpenSSF

### PR DESCRIPTION
**Pull request by JustinCappos**
This is effectively a typo change since CII has disbanded in favor of OpenSSF.  But I'm not sure if a broader procedure needs to be followed here because it is a change to the charter.  I hope this is a really simple accept and merge.

Signed-off-by: Justin Cappos <justincappos@gmail.com>

### CODE REVIEW

**Comment by lumjjb** [comment]
Hi @JustinCappos LGTM! do you mind helping to fix the lint and spelling checks?

**Review by lumjjb — APPROVED** [review]
LGTM

**Comment by PushkarJ** [comment]
Looks like there are some spell checks and lint failures. We will try to get these fixed in separate PR after discussion in the meeting within a week or so and then merge it after. Hope that's okay!

**Comment by PushkarJ** [comment]
Thank you to @brandtkeller for fixing the issues in the original markdown content 

@JustinCappos we might need rebase and resolving of conflicts to merge this. If you don't have cycles to do it yourself let me know and I can take stab and add a new commit on top of yours with merge conflict fixes :)

**Comment by ultrasaurus** [comment]
unfortunately, this is a copy of the text in the CNCF TOC repo: https://github.com/cncf/toc/blob/main/tags/security-charter.md -- @JustinCappos would you be up for making the change there too?

**Comment by JustinCappos** [comment]
I created https://github.com/cncf/toc/pull/994 for this.  If this is our
upstream, then we may want to pull down the file from there once it is
merged.

**Comment by anvega** [comment]
Resolved branch conflicts

**Pull request merged**
