### PR TITLE
Update cloud-native-security-whitepaper-simplified-chinese.md

### PR DESCRIPTION
**Pull request by zxb789**
i have retranslated some word to read more fluently in chinese

i consolidate #790 #791  in this one

### CODE REVIEW

**Comment by zxb789** [comment]
> i have retranslated some word to read more fluently in chinese
> 
> i consolidate #790 #791 in this one

@lumjjb can you help review this one ? thanks

**Comment by lumjjb** [comment]
Thanks @zxb789 ! 

@rootsongjc @babysor @Gsealy @hbris 

If you don't mind, can one of you take a quick review of this PR? Thanks!

**Review by babysor — APPROVED** [review]
LGTM

**Review by lumjjb — APPROVED** [review]
LGTM, thanks @babysor for reviewing!

**Pull request merged**
