### PR TITLE
Fix CI issues for Brazilian Portuguese white-paper

### PR DESCRIPTION
**Pull request by jralmaraz**
Slowly trying to address the issues on PT-BR white-paper version from CI:

https://github.com/cncf/tag-security/runs/6508469351?check_suite_focus=true

### CODE REVIEW

**Comment by jralmaraz** [comment]
Hi @lumjjb  - am I allowed to add brazilian portuguese to https://github.com/cncf/tag-security/blob/main/ci/spelling-config.json#L3 ? Or how is multiple languages planned to be handled in CI's spell check stage ? 

Thanks!

**Review by lumjjb — DISMISSED** [review]
Awesome!!! Thanks @jralmaraz !!! Going to run enable running the workflow!

**Comment by lumjjb** [comment]
I think it'll be fine if we just do `<!-- cspell:disable -->`, that should work for now!

**Comment by jralmaraz** [comment]
thanks @lumjjb ! Let's see the next CI run :)

**Review by lumjjb — APPROVED** [review]
🎉 All green! Thanks again @jralmaraz ! Welcome to the community!

**Pull request merged**
