### PR TITLE
Fix tiny typo in whitepaper chinese

### PR DESCRIPTION
**Pull request by sxmatch**
There is a tiny typo in chinese whitepaper which will mislead the
readers to understand. So fix it ASAP.

### CODE REVIEW

**Comment by lumjjb** [comment]
@Gsealy @babysor @zxb789  @mayocream any thoughts - if not will merge!

**Comment by Gsealy** [comment]
lgtm

**Review by lumjjb — APPROVED** [review]

**Comment by lumjjb** [comment]
@sxmatch can you sign your commit so it passes the DCO check? thanks!

**Comment by sxmatch** [comment]
> @sxmatch can you sign your commit so it passes the DCO check? thanks!

sure

**Pull request merged**
