### PR TITLE
Adding myself to the members list

### PR DESCRIPTION
**Pull request by ragashreeshekar**
I am Ragashree, I currently work as a Cloud Security Engineer at Nokia. 
I am contributing to CNCF CNS Map and CNS Lexicon projects

### CODE REVIEW

**Comment by ashutosh-narkar** [comment]
@ragashreeshekar can you please rebase to fix the conflict and then we can merge. Thanks !

**Comment by ultrasaurus** [comment]
Someone should also add a description or note about participation in the group.  I know @ragashreeshekar has already been active, but would need to look up the details.  

@ragashreeshekar feel free to add this yourself, or any reviewer can add those details before merging

**Comment by ragashreeshekar** [comment]
> 
> 
> Someone should also add a description or note about participation in the group. I know @ragashreeshekar has already been active, but would need to look up the details.
> 
> @ragashreeshekar feel free to add this yourself, or any reviewer can add those details before merging

Thanks @ultrasaurus, this indeed is a good practice and I have updated my intro and where I am currently contributing.

**Comment by ragashreeshekar** [comment]
> @ragashreeshekar can you please rebase to fix the conflict and then we can merge. Thanks !

Thanks @ashutosh-narkar, I have done the needful.

**Review by ultrasaurus — APPROVED** [review]

**Pull request merged**
