### PR TITLE
Removed Events Directory

### PR DESCRIPTION
**Pull request by eddie-knight**
Part of #1257 — Conceptualized in collaboration with @mrcdb and @brandtkeller.

The options we considered were as follows:

1. Move events to the top-level directory to enable blog-style formatting
2. Keep the events subdir in the community dir, but move them using the makefile to enable blog-style formatting
3. Stop tracking events in the main repo, instead relying on the blog for announcement
4. Stop trying to achieve the blog-style format and just track them in markdown pages

At the recommendation of @mrcdb, I've made this PR to implement option 3. @brandtkeller has volunteered to help create blog guidelines in a follow-up PR.

(Marco and Brandt, please comment to confirm that I've captured this correctly).

### CODE REVIEW

**Comment by brandtkeller** [comment]
Discussed the placement of recurring meetings in the `README.md` and removal of duplicate entries.  Moving to placement and announcement of point-in-time events in a blog serves a greater purpose of utilizing the blog. 

Agree on the creation of guidelines for the blog, and will propose potential opportunities for the production of content for the blog in the next Security TAG meeting.

**Review by brandtkeller — APPROVED** [review]
Discussed the placement of recurring meetings in the `README.md` and removal of duplicate entries.  Moving to placement and announcement of point-in-time events in a blog serves a greater purpose of utilizing the blog. 

Agree on the creation of guidelines for the blog and will propose potential opportunities for the production of content for the blog in the next Security TAG meeting.

**Comment by mrcdb** [comment]
@eddie-knight you got the options right :+1:  I confirm that option 3 makes the most sense to me as I don't see a huge impact in tracking future events in the blog area (also, few of the current blog entries are effectively about past events anyway).

**Review by mnm678 — COMMENTED** [review]
This looks good except the linter error. It looks like the link error is not created by this pr.

**Comment by eddie-knight** [comment]
@mnm678 I went ahead and added the linter fixes to this PR

**Comment by anvega** [comment]
It would be nice to keep the past events file in an archive directory, even if not shown on the site.

There is a lot of fun history here that otherwise the record would be lost.

**Comment by eddie-knight** [comment]
Good idea, I'll put up a change shortly

**Comment by eddie-knight** [comment]
I've added a blog post with the links to past talks. This can always change in the future, but it seemed like a good interim place to save the content.

@anvega let me know if I missed anything.

**Review by jkjell — APPROVED** [review]

**Pull request merged**
