### PR TITLE
Clean-up: Update settings.yml

### PR DESCRIPTION
**Pull request by Riaankl**
People and permissions have been moved to the [cncf/people/config.yml file](https://github.com/cncf/people/blob/main/config.yaml) making permissions in the local settings.yml file redundant.

Proposed updates:

- [x]  Remove the people from the local settings.yml
- [x]  Add a link in the setting.yml to the [cncf/people/config.yml file](https://github.com/cncf/people/blob/main/config.yaml#L892) for clarity

### CODE REVIEW

**Comment by PushkarJ** [comment]
@Riaankl thank you for the PR. Can you please add @lirantal in the new configuration file? He is the only one missing from the list we are removing.

**Comment by Riaankl** [comment]
> @Riaankl thank you for the PR. Can you please add @lirantal in the new configuration file? He is the only one missing from the list we are removing.

No problems @PushkarJ I can add @lirantal , with write permission? 
Which role does @lirantal have in the TAG?

**Comment by PushkarJ** [comment]
"Read" permission for @lirantal is what we have today so please do the same

**Comment by Riaankl** [comment]
@PushkarJ I created a [PR ](https://github.com/cncf/people/pull/395) for adding @lirantal to the config.yml file in cncf/people.

Can you please merge this PR as it is not dependent on the other PR.

Thanks!

**Review by PushkarJ — APPROVED** [review]

**Pull request merged**
