### PR TITLE
Remove actions and update self-assesment

### PR DESCRIPTION
**Pull request by jkowall**
I have updated the self-assesment to remove the "pending changes" part of the text and thank the Security Pals folks for the contribution to the project!

I have removed the actions.md file as well since the issue flagged there was corrected in July 2023 per [this Github advisory](https://github.com/jaegertracing/jaeger/security/advisories/GHSA-2w8w-qhg4-f78j).

### CODE REVIEW

**Comment by eddie-knight** [comment]
If this is ready to go, please be sure to update Line 26 to `complete`

**Review by JustinCappos — APPROVED** [review]
Okay, thanks for the update!  Really happy to see this!

**Review by anvega — APPROVED** [review]

**Comment by jkowall** [comment]
> Okay, thanks for the update! Really happy to see this!

Fixed on our repo too, so it points to your copy. Thanks to @eddie-knight for hounding me and helping with how this should work.

**Comment by eddie-knight** [comment]
@jkowall was this PR intentionally closed?

**Comment by jkowall** [comment]
No I thought it was merged.

**Comment by jkowall** [comment]
Okay I guess I wait for you to merge then :)

**Review by ragashreeshekar — APPROVED** [review]

**Pull request merged**
