### PR TITLE
CNSWP grammar fixes

### PR DESCRIPTION
**Pull request by szh**
Signed-off-by: Shlomo Heigh <shlomo.heigh@cyberark.com>

Fixes a few minor grammar errors that I found while recording for the audio version.
I also added a comment to the lint and links GH action files to describe how to run the processes manually on the whole repository (not just changed files). I then went ahead and fixed a few of those issues.

### CODE REVIEW

**Comment by szh** [comment]
There are a few lint and link errors, though they're not related to the changes in this PR:

- [x] Broken link to ntia.gov/sbom (fixed in this PR)
- [ ] Broken link to oreilly.com for security boundaries
- [ ] Markdown lint error for citations section: "Link and image reference definitions should be needed"

**Comment by ragashreeshekar** [comment]
@szh Thanks for the PR, please fix the lint issues and I will merge once done.

**Comment by szh** [comment]
@ragashreeshekar I've fixed all the lint/spelling/links issues that are easily fixable. The rest are mentioned in my comment above and are out of scope for this effort.

**Comment by lumjjb** [comment]
@ragashreeshekar The PR is ready - can you take another look and merge if it looks good!

**Review by PushkarJ — APPROVED** [review]

**Comment by PushkarJ** [comment]
Thank you so much @szh for fixing so many of the links, lints and spellchecks and other changes as well !!

**Pull request merged**
