### PR TITLE
Documenting the audio editing process.

### PR DESCRIPTION
**Pull request by apmarshall**
I'm sure additional information will be desired in this README, this is just my piece of the pie.

Signed-off-by: Alex Floyd Marshall <apmarshall@soren.tech>

### CODE REVIEW

**Comment by apmarshall** [comment]
@ragashreeshekar Here's the PR documenting the audio editing process.

**Comment by apmarshall** [comment]
Relates to https://github.com/cncf/tag-security/issues/953

**Comment by ragashreeshekar** [comment]
Thank you @apmarshall.
There are some lint errors, kindly resolve them and I could merge to the repo.

One suggestion would be to add this in the tag-security/audio-recordings/readme so it would be imperative we could use this for all our paper recordings.

**Comment by apmarshall** [comment]
I'll move it to that path and see if I can solve the linting errors.

**Comment by szh** [comment]
There are still some lint errors. Also, do you have the audacity script you used in step 1? It might be worth including it.

**Comment by ragashreeshekar** [comment]
@szh thanks for flagging it. 

[readme.md](https://github.com/cncf/tag-security/files/10407787/readme.md)
@apmarshall I have addressed the lint errors, kindly push these changes., and sign the commits. Thanks

**Comment by szh** [comment]
@apmarshall any update on this?

**Review by anvega — APPROVED** [review]

**Comment by anvega** [comment]
Squashed and merged

**Pull request merged**
