### PR TITLE
KubeVela security self assessment

### PR DESCRIPTION
**Pull request by wonderflow**
Signed-off-by: Jianbo Sun <jianbo.sjb@alibaba-inc.com>

Ref #976 

@IAXES

https://github.com/cncf/toc/pull/890

### CODE REVIEW

**Comment by lumjjb** [comment]
Tagging @IAXES - can you comment so i can assign you to the ticket?

**Comment by IAXES** [comment]
> Tagging @IAXES - can you comment so i can assign you to the ticket?

@lumjjb sure!

**Comment by ragashreeshekar** [comment]
@wonderflow Seems some Lint issues. 
Can you please address them?

**Comment by wonderflow** [comment]
@PushkarJ Hi, the linting CI seems to be too strict, can we make it more relax?

**Comment by wonderflow** [comment]
ping @PushkarJ  please help check, thanks

**Comment by anvega** [comment]
I don't know that in the past a self-assessment has ever been merged prior to the completion of the assessment. This is largely due to comments from reviewers and changes in response to those comments are expected. As a result, the document has a lot of changes happen to it during the process. In the interim, the document is linked in the issue. Going over the discussion in the issue, it looks the team is requiring for the document to be accessed and controlled which is fine.

**Comment by anvega** [comment]
Following my previous comment, we will only merge the assessment once the review is completed. I will close this PR for now. A final revised version will be merged once the assessment is completed. If you have any questions, please don't hesitate to contact me directly.

**Pull request closed without merging**
