### PR TITLE
Added questions related to access and code review

### PR DESCRIPTION
**Pull request by nir-valtman**

### CODE REVIEW

**Review by lumjjb — COMMENTED** [review]
ahh i wrote some comments  here but never hit the "submit review button"!

**Comment by lumjjb** [comment]
@nir-valtman  are you able to update the PR?

**Comment by szh** [comment]
@lumjjb Since @nir-valtman didn't respond, is it worthwhile for me to start a new PR with these changes so we can get them merged?

**Comment by anvega** [comment]
@nir-valtman Nudge here to see if you can resolve the above comments

**Comment by anvega** [comment]
Although, admittedly, the response from the tag here could have been more prompt, we'd like to proceed with some of the additional questions included here. Some could use some refinement or classification. @szh Given the lack of response from the submitter here, if you are still inclined to do so, would you mind starting a new pr as you proposed? In the meantime, I'll go ahead and close this for now.

**Pull request closed without merging**
