### PR TITLE
whitepaper README: wrap at 80 columns, add reference style links

### PR DESCRIPTION
**Pull request by ultrasaurus**
* wrap at 80 columns
* add reference style links to markdown more readable and wrapping easier
* lint fix: Lists should be surrounded by blank lines (add blank line before list of links at the bottom)
* add reference to acronym at beginning (sorry prolly should have been formatting-only, but figured this change would be non-controversial)

### CODE REVIEW

**Review by lumjjb — DISMISSED** [review]
LGTM

**Comment by lumjjb** [comment]
looks like linter is still complaining:

```
security-whitepaper/README.md:97 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
security-whitepaper/README.md:103:85 MD047/single-trailing-newline Files should end with a single newline character
1
```

**Comment by ultrasaurus** [comment]
@lumjjb  ok, now I think I've fixed all the lint errors

**Review by TheFoxAtWork — APPROVED** [review]
LGTM

**Pull request merged**
