### PR TITLE
add  use-cases-wp.doc to compliance folder

### PR DESCRIPTION
**Pull request by hubbertsmith**

### CODE REVIEW

**Comment by eddie-knight** [comment]
Hey @hubbertsmith, since this is an empty file I'm gonna change this PR to a draft for now. When you have content committed and ready for review, all you'll need to do is add a description to the PR and take it out of draft mode.

**Comment by hubbertsmith** [comment]
Cool. No problem
I'll attach the doc shortly

**Comment by hubbertsmith** [comment]
[CNCF Compliance WG Use Case v04.docx](https://github.com/user-attachments/files/16116368/CNCF.Compliance.WG.Use.Case.v04.docx)

**Comment by hubbertsmith** [comment]
Hi , I attached the compliance whitepaper document in comments ... I was
unable to find another method to attach (I have limited GIT privs)
LMK if i should do it differently. and feel free to lend a hand to put the
doc where it needs to be

**Comment by anvega** [comment]
Thanks, @hubbertsmith! So, GitHub is designed primarily for code and text-based files. Word (.doc) files are binary formats that GitHub can't render or preview directly in the web interface.

Couple steps:

## Convert to Markdown:

1. Open your Word document
2. Copy the content
3. Paste into a markdown editor (e.g., VS Code with markdown extension, online tools like StackEdit)
4. Format your content using markdown syntax:
   - Use # for headings (e.g., # Heading 1, ## Heading 2)
   - Use - for bullet points
   - Use 1. 2. 3. for numbered lists
   - Enclose text in ** for bold, * for italic
5. Save the file with a .md extension (e.g., compliance_usecases.md)

## Add to Your Branch:

1. Ensure you're on your `hubbertsmith:patch-1` branch
2. Add the new markdown file to your repository
3. Commit the changes
4. Push to your branch on GitHub

If the document must remain in Word format, you can still add it to the repository, but users will need to download it to view the content

**Comment by hubbertsmith** [comment]
thanks for your kind response
i use .md all the time
this is a DOC file, it has ms-word formatting/tables/toc. Doc files can be
reviewed by a clone. can we go that way?


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
*CEO, ***@***.*** Ops *
* ... i4 Zero Exfil accelerates data-driven innovation. Prevents data
breach in minutes not months. ... Even credentialed users and 3rd parties
cannot walk away with data. *
https://calendly.com/hubbert/60min

**Comment by anvega** [comment]
Thank you for your explanation. I understand your situation better now. However, I want to clarify a few points about our repository practices:

We don't currently have any .doc files in our repository. Instead, we use links to Google Docs and PDFs for content with complex formatting. PDFs are proofed and designed by CNCF tech writers which can be done by opening a ticket with them.

For your document, we suggest the following options:
   a. Convert the file to a Google Doc and provide a link in the README.md file. This maintains formatting while allowing easy access and collaborative editing.
   b. Convert to markdown. While you mentioned formatting, tables, and ToC as potential issues, these are actually quite manageable in markdown. I'd be happy to assist you with this conversion early next week if you'd like.

If you prefer to keep it as a .doc file, please note that while Git can version control .doc files, it won't be able to show meaningful diffs on GitHub's web interface. This makes reviewing changes more difficult. If you decide to stick with the .doc format for now, we can certainly work with that. You can add it to your hubbertsmith:patch-1 branch, and reviewers will need to clone the repository and open it with Word to review it fully.

Let me know which option you prefer, or if you have any questions about these approaches. We're here to help make this process as smooth as possible for you.

**Comment by hubbertsmith** [comment]
Hiya.
Happy to do this. Google doc is a great suggestion.
What's the upload link?

**Comment by anvega** [comment]
I've taken the liberty of uploading your file to our shared Google Drive and granting you editor rights. You can now access and edit the document here:

https://docs.google.com/document/d/1l_4HHtYVXG2dG5Y1WRzmMrdt_IcTqMHPL8u6ZQ1Zc9A

**Comment by hubbertsmith** [comment]
my hero, thank you so much
I will add the link to the compliance/readme.md

CHEERS
h
***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
*CEO, ***@***.*** Ops *
* ... i4 Zero Exfil accelerates data-driven innovation. Prevents data
breach in minutes not months. ... Even credentialed users and 3rd parties
cannot walk away with data. *
https://calendly.com/hubbert/60min

**Comment by hubbertsmith** [comment]
hi Andres, I updated this doc ... is there anything else I should do to
follow process and work nicely with others?

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
*CEO, ***@***.*** Ops *
* ... i4 Zero Exfil accelerates data-driven innovation. Prevents data
breach in minutes not months. ... Even credentialed users and 3rd parties
cannot walk away with data. *
https://calendly.com/hubbert/60min

**Pull request closed without merging**
