### PR TITLE
[WIP] Add Platform Uploads

### PR DESCRIPTION
**Pull request by pbaderia01**
Added the following folders:
  1. uploads - Since the community is gonna be active on multiple platforms going forward and all platforms have their own requirements for uploads, this folder can act as a central repository to make sure that all uploads in the required formats are added here for review as well as for future reference.

Added the following files:
  1. community-platform-bg.png - The community platform requires the image to be in 2560*650 resolution and in jpg/png format. Reorganised the logo and the text a bit to comply with that.
  2. community-platform-logo.png - The community platform requires the logo to be in 400*400 resolution and in jpg/png format. Removed the text to comply with the same.

More details here: https://github.com/cncf/tag-security/issues/692

Signed-off-by: Piyush Baderia <piyush.baderia@outlook.com>

### CODE REVIEW

**Comment by lumjjb** [comment]
Can you add a `README.md` to talk about what type of files should be in the folder (somewhat like what you've described in the PR comment)

**Review by TheFoxAtWork — CHANGES_REQUESTED** [review]
The new folder needs a README.md that provides how it is used and what is expected.  I also recommend ensuring the readme lists the files and the constraints of the files (such as is in the PR comment)

**Comment by pbaderia01** [comment]
Hey @lumjjb @TheFoxAtWork I will be working on modifying these images further (the last time we tried uploading them on to that platform they didn't look so good) and along with the updated images I will also push the Readme. Unfortunately I'm not able to mark this PR as Draft. Could you please do that for me?

**Comment by anvega** [comment]
Already covered in design folder https://github.com/cncf/tag-security/tree/main/design

**Pull request closed without merging**
