### PR TITLE
docs: adding reference article

### PR DESCRIPTION
**Pull request by lirantal**
Adding another reference article with regards to the Colors and Faker npm modules incident

### CODE REVIEW

**Comment by lirantal** [comment]
The build is broken due to cspell but not on any spelling issues, but rather on the fact it can't run due to unsupported Node.js version of the workflow. Looking into it...

**Review by lumjjb — APPROVED** [review]
LGTM!

**Comment by lumjjb** [comment]
Looks good - seems like there's a DCO check enabled now as well, would you be able to add a sign off to your commits? 

Yea - we will have to take a look at the cspell issue - would you mind raising an issue for this?

**Comment by lumjjb** [comment]
re: cspell - may be a flake actually, after fixing the DCO let's see if it comes up again..

**Comment by lirantal** [comment]
Yep, I'll work out the signed commits later in this PR and the others, no worries.
Thanks for quickly taking a look at it!

**Pull request merged**
