### PR TITLE
Update remove APAC meeting (no longer running)

### PR DESCRIPTION
**Pull request by lumjjb**

### CODE REVIEW

**Review by TheFoxAtWork — APPROVED** [review]
LGTM - would recommend providing a way for folks interested in setting up a region specific meeting to do so with the leadership team so we can support them.

**Comment by lumjjb** [comment]
Created https://github.com/cncf/tag-security/issues/886 to track your suggestion!

**Review by JustinCappos — APPROVED** [review]
Agreed we should drop this.    

I wish we could have gotten more momentum here...  :(

**Comment by PushkarJ** [comment]
Should we wait to merge this until we can close out on https://github.com/cncf/tag-security/issues/886 ?

**Comment by lumjjb** [comment]
don't think we have to wait since we do have a tracking issue and don't want folks to try to dial in to the meeting

**Pull request merged**
