### PR TITLE
docs: add Liran Tal to reviewers for supply chain security docs

### PR DESCRIPTION
**Pull request by lirantal**
Signed-off-by: Liran Tal <liran.tal@gmail.com>

### CODE REVIEW

**Review by TheFoxAtWork — APPROVED** [review]
Thrilled to have another talented security professional assist in managing the supply chain attack catalog with @SantiagoTorres !

**Comment by TheFoxAtWork** [comment]
@lumjjb @achetal01 @sublimino  This needs at least two of you to approve since it changes permissions in the repo.

**Comment by lumjjb** [comment]
There is a current restriction around CODEOWNERS now that it requires the user to have certain permission bits on the repo... Let's work this out - https://github.com/cncf/tag-security/issues/947 (we will discuss this at the next leadership meeting)

**Comment by lumjjb** [comment]
We are not adding additional permissions. we've opted for a bot to help provide more granular notifications for this. @PushkarJ 's PR https://github.com/cncf/tag-security/pull/970 fixes this!

**Comment by PushkarJ** [comment]
@lirantal with #970 now merged, would you be willing to make a one-line change to add your Github handle to this list: https://github.com/cncf/tag-security/blob/main/.github/auto_request_review.yml#L28-L33 ? 

This will allow you to get rotated in round robin fashion for any reviews related to supply chain security which I believe was the intent of this PR. Let me know if you have any questions :)

**Comment by lirantal** [comment]
PR opened and waiting to merge and then close this one.

**Pull request closed without merging**
