### PR TITLE
Security Pals retrospective slides

### PR DESCRIPTION
**Pull request by jlk**
Adding a markdown version of the powerpoint deck I used at a STAG meeting to give a retrospective of the "Security PALS" pilot documented in #554.

I've written this for [Marp presentation system](https://marp.app/) which seems to render OK as plan markdown, but if folks think that's overkill, I'll remove the extra markup.

### CODE REVIEW

**Comment by TheFoxAtWork** [comment]
Thank you so much for pulling this together!! (It's been a while but I'm thrilled this seems fruitful!)

I'd love for security pals to engage with accepted sandbox security projects (minimally) as they are under the TAG's domain.  I suspect plenty of other projects would also gain value from this - not just sandbox.  Outreach would certainly be a good start, but also allowing projects to come to the TAG and ask for assistance.  These were some of the original intentions around this.

**Comment by JustinCappos** [comment]
@jlk @TheFoxAtWork There will be a meeting on Monday, July 31st at 1PM Eastern about how Security Pals, Security assessments, Lightweight threat modeling should be combined.  ( https://zoom.us/j/99063331512?pwd=WlFFMGhWM2FhcGtDaVJJSm5peDk5Zz09 ).  Please feel free to invite anyone who has an opinion on this topic.

**Comment by TheFoxAtWork** [comment]
Thanks Justin!  I won't be able to attend, however be sure to reflect this in the monthly TAG update to the TOC with your liaisons' awareness.

**Comment by PushkarJ** [comment]
@JustinCappos do we have any suggestions for @jlk for this PR, based on the outcomes of the meeting held on July 31? 

cc @sublimino

**Comment by JustinCappos** [comment]
@jlk Based upon what we learned from your experience and our discussion, we are going in a different direction with some aspects of this.  From what we've decided, there is overlap, but enough differences that I'm a little concerned that having these slides as is will be confusing. 

I will close this for now, but am open to discussion about how to make modifications to accept this.  However, I don't think it's a good idea to take it as it is now.

**Pull request closed without merging**
