### PR TITLE
Update cloud-native-security-whitepaper-simplified-chinese.md

### PR DESCRIPTION
**Pull request by Alex-null**
I have retranslated some words try to read more fluently.

### CODE REVIEW

**Comment by TheFoxAtWork** [comment]
@lumjjb please take a look.

**Comment by lumjjb** [comment]
Thanks @Alex-null 

@rootsongjc @babysor @Gsealy @Hbris

If you don't mind, can one of you take a quick review of this PR? Thanks!

**Comment by Gsealy** [comment]
LGTM

**Review by babysor — APPROVED** [review]
LGTM. It makes more sense.

**Review by lumjjb — APPROVED** [review]
Thanks @Gsealy @babysor for the reviews! LGTM

**Pull request merged**
